<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">


    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="/css/bootstrap-theme.css" rel="stylesheet">
    <link href="/css/my-style.css" rel="stylesheet">

    <title>Server-Side Programming - <?php echo $view->pageTitle; ?></title>
</head>

<body role=""document">

<div class="container">
        <div  class="row">
            <div id="title" class="col-xs-12">
                <img src="images/new_uos_logo.jpg" alt="Salford University" />
                    <div class="pull-right"> <h1><?php echo $view->pageTitle ?> </h1></div>

            </div>
        </div>


    <div class="row">
        <div id="menu" class="col-xs-6 col-sm-3 col-md-2">
        <ul class="nav navbar_default nav-stacked">

        </ul>
            <?php

            if (!isset($_SESSION["login"])) {
                echo ' 
            <form method="post" action="" class="form text-primary">
                <label for="username">Username</label>
                <input type="text" name="username">
                <label for="password">Password</label>
                <input type="text" name="password">
                <input type="submit" name="loginbutton" value="Login">

            </form>';
            }
            else
            {
            echo '
            <form method="post" action="" class="form text-primary">
                <input type="submit" name="logoutbutton" value="Logout">
            </form>';
            }
            ?>

            <li><a href="index.php">Home</a></li>
            <li><a href="page1.php">Page1</a></li>
            <li><a href="page2.php">Page2</a></li>
        </ul>
       </div>

    <div id="content" class="col-xs-6 col-sm-9 col-md-10">



